# GET http://localhost:3000/api/books
# Content-Type: application/json

# {
#     "bookCodes": ["JK-45", "SHR-1"],
#     "memberCode": "M001"
# }

get http://localhost:3000/api/books
Content-Type: application/json

{
    "bookCodes": ["JK-45"],
    "memberCode": "M001"
}